// In-Memory Data Store Fallback for High-Speed Development & Testing
// Contains 50 Verified Kopargaon Teachers & Tutors Categorized by Grade Tier

export const memoryStore = {
  tutors: [
    // ==========================================
    // TIER 1: GRADE 5TH TO 8TH STANDARD (MIDDLE SCHOOL FOUNDATION)
    // ==========================================
    {
      id: "tut-kp-001",
      name: "Dr. Rajesh Deshmukh",
      title: "Ph.D. Applied Mathematics (IIT Bombay) | 12+ Yrs Exp",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1200,
      rating: 4.98,
      totalReviews: 84,
      subjects: ["Mathematics", "Physics", "Vedic Maths"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard", "9th Standard", "10th Standard", "11th Standard", "12th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Former Assistant Professor & Premier Educator. Specializes in Higher Mathematics, Vedic Speed Maths, and Board Excellence in Kopargaon.",
      qualification: "Ph.D. in Applied Mathematics (IIT Bombay)",
      experienceYears: 12
    },
    {
      id: "tut-kp-006",
      name: "Sunita Jadhav",
      title: "B.Sc B.Ed (Pune University) | Science & Math Foundation Specialist",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      location: "Samata Nagar, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 550,
      rating: 4.92,
      totalReviews: 42,
      subjects: ["Mathematics", "Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Patient middle school educator focusing on building strong mathematical fundamentals, conceptual clarity, and visual science experiments.",
      qualification: "B.Sc B.Ed (Pune University)",
      experienceYears: 8
    },
    {
      id: "tut-kp-007",
      name: "Rameshwar Shinde",
      title: "M.Sc Mathematics | Vedic Maths & Mental Arithmetic Coach",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Center, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 600,
      rating: 4.89,
      totalReviews: 38,
      subjects: ["Mathematics", "Vedic Maths"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Vedic Mathematics specialist. Helps 5th to 8th grade Kopargaon students eliminate math fear through mental calculation tricks.",
      qualification: "M.Sc Mathematics",
      experienceYears: 10
    },
    {
      id: "tut-kp-008",
      name: "Kavita Thorat",
      title: "M.A. English B.Ed | Grammar & Reading Mastery Coach",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 500,
      rating: 4.88,
      totalReviews: 35,
      subjects: ["English Literature"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Specializes in developing strong English vocabulary, grammar foundations, creative writing, and spoken English confidence for young learners.",
      qualification: "M.A. English, B.Ed",
      experienceYears: 7
    },
    {
      id: "tut-kp-009",
      name: "Anand Kulkarni",
      title: "B.Tech (COEP Pune) | STEM & Practical Science Mentor",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Online Only",
      hourlyRate: 650,
      rating: 4.94,
      totalReviews: 47,
      subjects: ["Science", "Computer Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Engaging STEM coach teaching 5th-8th std students foundational physics, basic electronics, and scratch programming with visual kits.",
      qualification: "B.Tech Mechanical (COEP)",
      experienceYears: 6
    },
    {
      id: "tut-kp-010",
      name: "Sneha More",
      title: "B.Sc Chemistry B.Ed | Middle School General Science",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80",
      location: "Kankuri Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 480,
      rating: 4.86,
      totalReviews: 29,
      subjects: ["Science", "Chemistry"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Dedicated science educator making chemistry and environmental science easy to remember using real-world analogies and charts.",
      qualification: "B.Sc Chemistry, B.Ed",
      experienceYears: 5
    },
    {
      id: "tut-kp-011",
      name: "Deepak Salunke",
      title: "M.Sc Physics | Middle School Physics Concepts & Numericals",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80",
      location: "Subhash Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 580,
      rating: 4.90,
      totalReviews: 36,
      subjects: ["Physics", "Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Focuses on light, sound, motion, and electricity fundamentals for 6th to 8th standard students preparing for high school science.",
      qualification: "M.Sc Physics",
      experienceYears: 8
    },
    {
      id: "tut-kp-012",
      name: "Aarti Gawande",
      title: "B.A. B.Ed | Social Studies, Geography & History Specialist",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      location: "Yeshwant Nagar, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 450,
      rating: 4.85,
      totalReviews: 31,
      subjects: ["English Literature", "Social Studies"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Makes history and geography storytelling sessions interactive with maps, timeline games, and structured textbook notes.",
      qualification: "B.A. Geography, B.Ed",
      experienceYears: 9
    },
    {
      id: "tut-kp-013",
      name: "Nitin Bhange",
      title: "B.C.A. | Computer Fundamentals & Digital Literacy",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80",
      location: "Tilak Nagar, Kopargaon",
      mode: "Online Only",
      hourlyRate: 520,
      rating: 4.88,
      totalReviews: 24,
      subjects: ["Computer Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Teaches 5th to 8th std students computer fundamentals, MS Office, basic HTML, and computational logic thinking.",
      qualification: "B.C.A. (Bachelor of Computer Applications)",
      experienceYears: 5
    },
    {
      id: "tut-kp-014",
      name: "Swati Londhe",
      title: "M.Sc Mathematics | Geometry & Algebra Drill Coach",
      avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 560,
      rating: 4.91,
      totalReviews: 40,
      subjects: ["Mathematics"],
      gradeTier: "5th to 8th Standard",
      classes: ["6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Specialist in middle school algebra equations, fractions, decimals, and Euclidean geometry fundamentals.",
      qualification: "M.Sc Mathematics",
      experienceYears: 7
    },
    {
      id: "tut-kp-015",
      name: "Rahul Wagh",
      title: "B.Sc Biology | Environmental Science & Life Science Coach",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80",
      location: "Shirdi Highway, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 490,
      rating: 4.87,
      totalReviews: 27,
      subjects: ["Biology", "Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Passionate about plants, human body systems, and ecosystem science. Conducts nature walks and visual biological diagram sessions.",
      qualification: "B.Sc Zoology",
      experienceYears: 6
    },
    {
      id: "tut-kp-016",
      name: "Archana Pawar",
      title: "M.A. Language & Literature | Foundation Grammar & Writing",
      avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=250&q=80",
      location: "Market Area, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 420,
      rating: 4.84,
      totalReviews: 33,
      subjects: ["English Literature"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "11 years experience teaching language arts, essay writing, comprehension skills, and vocabulary building.",
      qualification: "M.A., B.Ed",
      experienceYears: 11
    },
    {
      id: "tut-kp-017",
      name: "Ganesh Chaudhari",
      title: "M.Sc Applied Maths | NMMS & Olympiad Foundation Coach",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Bus Stand Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 620,
      rating: 4.93,
      totalReviews: 44,
      subjects: ["Mathematics", "Vedic Maths"],
      gradeTier: "5th to 8th Standard",
      classes: ["6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Prepares Kopargaon students for 8th Std NMMS scholarship exam and Junior Mathematics Olympiads.",
      qualification: "M.Sc Mathematics",
      experienceYears: 9
    },
    {
      id: "tut-kp-018",
      name: "Pallavi Sonawane",
      title: "B.Tech Computer Science | Creative Coding & Logic Trainer",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Online Only",
      hourlyRate: 550,
      rating: 4.89,
      totalReviews: 22,
      subjects: ["Computer Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Young software engineer introducing middle school students to block coding, web page basics, and game logic.",
      qualification: "B.Tech IT",
      experienceYears: 4
    },
    {
      id: "tut-kp-019",
      name: "Vijay Kharde",
      title: "M.Sc Botany | Science Projects & Practical Experimentation",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Samata Nagar, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 500,
      rating: 4.87,
      totalReviews: 28,
      subjects: ["Biology", "Science"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Focuses on plant biology, microscopic observations, and science exhibition project design for Kopargaon schools.",
      qualification: "M.Sc Botany",
      experienceYears: 8
    },
    {
      id: "tut-kp-020",
      name: "Radhika Joshi",
      title: "B.Sc B.Ed | All-Subject Primary & Middle School Tutor",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 480,
      rating: 4.86,
      totalReviews: 35,
      subjects: ["Mathematics", "Science", "English Literature"],
      gradeTier: "5th to 8th Standard",
      classes: ["5th Standard", "6th Standard", "7th Standard", "8th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Comprehensive 1-on-1 home tutor covering homework, daily revision, and exam preparation across all subjects.",
      qualification: "B.Sc B.Ed",
      experienceYears: 10
    },

    // ==========================================
    // TIER 2: GRADE 9TH TO 10TH STANDARD (HIGH SCHOOL BOARD SPECIALISTS)
    // ==========================================
    {
      id: "tut-kp-002",
      name: "Sunita Patil",
      title: "M.Sc Physics (Pune University) | Senior High School Physics Faculty",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      location: "Samata Nagar, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 950,
      rating: 4.95,
      totalReviews: 62,
      subjects: ["Physics", "Mathematics"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Top-rated physics mentor in Kopargaon. Builds strong conceptual clarity in 10th Board Mechanics, Electricity & Optics.",
      qualification: "M.Sc Physics (Pune University)",
      experienceYears: 9
    },
    {
      id: "tut-kp-004",
      name: "Priyanka Kulkarni",
      title: "M.Sc Organic Chemistry | State Board 10th Topper Mentor",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      location: "Shirdi Highway, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 850,
      rating: 4.91,
      totalReviews: 47,
      subjects: ["Chemistry", "Biology"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "10+ years coaching Chemistry & Science in Kopargaon. Simplifies chemical bonding, equations, and 10th board paper patterns.",
      qualification: "M.Sc Organic Chemistry",
      experienceYears: 10
    },
    {
      id: "tut-kp-005",
      name: "Vikas Jadhav",
      title: "M.A. English Literature, B.Ed | High School English Specialist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Kankuri Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 750,
      rating: 4.88,
      totalReviews: 39,
      subjects: ["English Literature"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "High school English literature and grammar expert. Guides students through board paper writing rubrics and prose analysis.",
      qualification: "M.A. English, B.Ed",
      experienceYears: 11
    },
    {
      id: "tut-kp-021",
      name: "Sanjay Nikam",
      title: "M.Sc Mathematics | 10th Board Algebra & Geometry Master Coach",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 900,
      rating: 4.96,
      totalReviews: 78,
      subjects: ["Mathematics"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "14 years of 10th board math coaching experience. Produced multiple 100/100 math scores in Kopargaon CBSE & State Board exams.",
      qualification: "M.Sc Mathematics",
      experienceYears: 14
    },
    {
      id: "tut-kp-022",
      name: "Madhuri Tribhuwan",
      title: "M.Sc Zoology | 10th Biology & Human Physiology Specialist",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 800,
      rating: 4.92,
      totalReviews: 51,
      subjects: ["Biology", "Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Focuses on 10th Board biology diagrams, life processes, genetics, and environment chapters with step-wise mark scoring guidance.",
      qualification: "M.Sc Zoology, B.Ed",
      experienceYears: 8
    },
    {
      id: "tut-kp-023",
      name: "Santosh Auti",
      title: "M.Sc Chemistry | 10th Reaction Mechanism & Periodic Table Expert",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 850,
      rating: 4.93,
      totalReviews: 58,
      subjects: ["Chemistry", "Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Simplifies 10th grade carbon compounds, metals-nonmetals, and chemical reactions for board exam high scores.",
      qualification: "M.Sc Organic Chemistry",
      experienceYears: 12
    },
    {
      id: "tut-kp-025",
      name: "Mahesh Kakade",
      title: "M.A. History & Civics | 10th Social Science Board Specialist",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80",
      location: "Subhash Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 700,
      rating: 4.87,
      totalReviews: 43,
      subjects: ["Social Studies"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "13 years helping 10th board students master history events, geography map plotting, and economics answer structuring.",
      qualification: "M.A. History, B.Ed",
      experienceYears: 13
    },
    {
      id: "tut-kp-027",
      name: "Shital Gunjal",
      title: "M.Sc Physics | 10th CBSE Light, Electricity & Energy Expert",
      avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=250&q=80",
      location: "Yeshwant Nagar, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 820,
      rating: 4.90,
      totalReviews: 37,
      subjects: ["Physics", "Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Specializes in ray diagrams, circuit problem solving, and magnetic effects of electric current for 10th board aspirants.",
      qualification: "M.Sc Physics",
      experienceYears: 7
    },
    {
      id: "tut-kp-028",
      name: "Pravin Bangar",
      title: "B.E. Mechanical | 10th Math HOTS & Problem Solving Coach",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80",
      location: "Tilak Nagar, Kopargaon",
      mode: "Online Only",
      hourlyRate: 880,
      rating: 4.94,
      totalReviews: 61,
      subjects: ["Mathematics", "Physics"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Engineer educator focusing on quadratic equations, surface areas, volumes, and 10th board sample paper speed drills.",
      qualification: "B.E. Mechanical Engineering",
      experienceYears: 10
    },
    {
      id: "tut-kp-029",
      name: "Rohini Shelke",
      title: "M.Sc Biotechnology | 9th & 10th Science & Lab Practical Trainer",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80",
      location: "Kankuri Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 800,
      rating: 4.89,
      totalReviews: 34,
      subjects: ["Biology", "Chemistry"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Combines 9th/10th science theory with practical laboratory techniques and biology cell structure visualizations.",
      qualification: "M.Sc Biotechnology",
      experienceYears: 9
    },
    {
      id: "tut-kp-030",
      name: "Dnyaneshwar Bhor",
      title: "M.A. English | 10th ICSE & CBSE Board Grammar Specialist",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Bus Stand Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 780,
      rating: 4.91,
      totalReviews: 48,
      subjects: ["English Literature"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["ICSE", "CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "15 years experience preparing Kopargaon students for ICSE & CBSE Class 10 Board English Literature & Language papers.",
      qualification: "M.A. English, B.Ed",
      experienceYears: 15
    },
    {
      id: "tut-kp-031",
      name: "Sunita Nagare",
      title: "M.Sc Mathematics | 10th Trigonometry & Coordinate Geometry",
      avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=250&q=80",
      location: "Market Area, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 860,
      rating: 4.95,
      totalReviews: 55,
      subjects: ["Mathematics"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Expert guidance in 10th trigonometry identities, heights and distances, and coordinate geometry proofs.",
      qualification: "M.Sc Mathematics",
      experienceYears: 11
    },
    {
      id: "tut-kp-032",
      name: "Ajay Parjane",
      title: "M.C.A. | Class 10 Computer Applications (Python & Java)",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Online Only",
      hourlyRate: 850,
      rating: 4.92,
      totalReviews: 41,
      subjects: ["Computer Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Teaches Class 9 & 10 Computer Applications curriculum, Python syntax, BlueJ Java object-oriented programming.",
      qualification: "M.C.A. (Master of Computer Applications)",
      experienceYears: 8
    },
    {
      id: "tut-kp-033",
      name: "Yogita Rahane",
      title: "M.Sc Chemistry | 9th & 10th CBSE Science Excellence Coach",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      location: "Samata Nagar, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 790,
      rating: 4.88,
      totalReviews: 32,
      subjects: ["Chemistry", "Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Focuses on step-wise written board answers, chemical formula balancing, and chapter-end exercise drill.",
      qualification: "M.Sc Chemistry",
      experienceYears: 7
    },
    {
      id: "tut-kp-034",
      name: "Kiran Deokar",
      title: "M.Sc Physics | 10th Board Physics Numericals Specialist",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80",
      location: "Shirdi Highway, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 870,
      rating: 4.93,
      totalReviews: 49,
      subjects: ["Physics"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "10 years experience helping high school students master 10th Physics numericals, SI units, and formula derivations.",
      qualification: "M.Sc Physics",
      experienceYears: 10
    },
    {
      id: "tut-kp-035",
      name: "Varsha Hingane",
      title: "M.Sc Environmental Science | 10th Biology & Physiology",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 810,
      rating: 4.87,
      totalReviews: 30,
      subjects: ["Biology", "Science"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Specialist in 10th board life processes, reproduction, heredity, and environmental biology chapters.",
      qualification: "M.Sc Environmental Science",
      experienceYears: 8
    },
    {
      id: "tut-kp-036",
      name: "Amol Wabale",
      title: "M.A. Geography B.Ed | 10th Social Science Map & Board Work",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 720,
      rating: 4.86,
      totalReviews: 36,
      subjects: ["Social Studies"],
      gradeTier: "9th to 10th Standard",
      classes: ["9th Standard", "10th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "12 years experience conducting map plotting drills, history answer writing templates, and civics test series.",
      qualification: "M.A. Geography, B.Ed",
      experienceYears: 12
    },

    // ==========================================
    // TIER 3: GRADE 11TH TO 12TH STANDARD (SENIOR SEC, ENTRANCE PREP & STREAM EXPERTS)
    // ==========================================
    {
      id: "tut-kp-003",
      name: "Amitabh Joshi",
      title: "B.Tech Computer Science (COEP Pune) | 11th/12th Coding & Math Educator",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Sangamner Road, Kopargaon",
      mode: "Online Only",
      hourlyRate: 1100,
      rating: 4.92,
      totalReviews: 53,
      subjects: ["Computer Science", "Mathematics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Software Engineer turned educator. Teaches Python, Data Structures, CBSE CS curriculum, and 12th Math.",
      qualification: "B.Tech CS (College of Engineering Pune)",
      experienceYears: 7
    },
    {
      id: "tut-kp-024",
      name: "Neha Landge",
      title: "Chartered Accountant (CA) | 11th & 12th Commerce & Economics Specialist",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=250&q=80",
      location: "Bus Stand Road, Kopargaon",
      mode: "Online Only",
      hourlyRate: 1250,
      rating: 4.97,
      totalReviews: 45,
      subjects: ["Accountancy & Economics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Practicing Chartered Accountant guiding Kopargaon 11th & 12th Commerce students in Accountancy, Financial Statements & Economics.",
      qualification: "CA, B.Com",
      experienceYears: 9
    },
    {
      id: "tut-kp-026",
      name: "Meenal Thorat",
      title: "Chartered Accountant (CA) | 11th & 12th Accountancy & CA Foundation",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Market, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1300,
      rating: 4.96,
      totalReviews: 41,
      subjects: ["Accountancy & Economics", "Mathematics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Practicing CA teaching 11th & 12th Commerce. Specializes in Accountancy, GST basics, micro & macro economics.",
      qualification: "CA, M.Com",
      experienceYears: 8
    },
    {
      id: "tut-kp-037",
      name: "Dr. Avinash Tambe",
      title: "Ph.D. Physics (IIT Kharagpur) | 11th/12th Physics JEE & MHT-CET Faculty",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1400,
      rating: 4.98,
      totalReviews: 92,
      subjects: ["Physics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Former IIT research fellow. 15 years coaching Kopargaon students for 12th Board Physics, JEE Main/Advanced & MHT-CET.",
      qualification: "Ph.D. Physics (IIT Kharagpur)",
      experienceYears: 15
    },
    {
      id: "tut-kp-038",
      name: "Dr. Smita Kadam",
      title: "M.D. & M.Sc Bio | 11th/12th Biology NEET & Board Medical Mentor",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1350,
      rating: 4.97,
      totalReviews: 88,
      subjects: ["Biology"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Doctor & senior biology educator specializing in 12th Board Biology NCERT line-by-line preparation & NEET Medical entrance.",
      qualification: "M.D., M.Sc Bio",
      experienceYears: 13
    },
    {
      id: "tut-kp-039",
      name: "Prof. Nilesh Shinde",
      title: "M.Tech Chemical Engg | 11th/12th Organic & Physical Chemistry",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 1200,
      rating: 4.94,
      totalReviews: 67,
      subjects: ["Chemistry"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "11 years teaching 11th & 12th Organic Chemistry reaction mechanisms, electrochemistry, and coordination compounds.",
      qualification: "M.Tech Chemical Engineering",
      experienceYears: 11
    },
    {
      id: "tut-kp-040",
      name: "Sachin Wakchaure",
      title: "M.Sc Mathematics | 11th/12th Higher Math & Calculus Specialist",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80",
      location: "Samata Nagar, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1150,
      rating: 4.95,
      totalReviews: 74,
      subjects: ["Mathematics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Specializes in 12th Board Integration, Differentiation, Vectors, 3D Geometry, and MHT-CET Mathematics speed drills.",
      qualification: "M.Sc Mathematics",
      experienceYears: 12
    },
    {
      id: "tut-kp-041",
      name: "Pooja Deshmukh",
      title: "FCA, B.Com (H) | 11th/12th Accountancy & CA Foundation Coach",
      avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=250&q=80",
      location: "Market Area, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1300,
      rating: 4.91,
      totalReviews: 49,
      subjects: ["Accountancy & Economics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "ICSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Fellow Chartered Accountant teaching partnership accounts, company balance sheets, and CA Foundation entry.",
      qualification: "FCA, B.Com (H)",
      experienceYears: 9
    },
    {
      id: "tut-kp-042",
      name: "Tushar Borawake",
      title: "M.Sc Physics | 12th Board & MHT-CET Ray Optics & Modern Physics",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80",
      location: "Kankuri Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 1180,
      rating: 4.92,
      totalReviews: 53,
      subjects: ["Physics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "10 years coaching 12th State Board Physics. Master in semiconductor devices, wave optics, and electromagnetic induction.",
      qualification: "M.Sc Physics",
      experienceYears: 10
    },
    {
      id: "tut-kp-043",
      name: "Priyanka Harde",
      title: "M.Sc Biochemistry | 12th Biology Genetics & Biotechnology Expert",
      avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=250&q=80",
      location: "Subhash Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1100,
      rating: 4.90,
      totalReviews: 44,
      subjects: ["Biology"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Biochemistry educator focusing on 12th NCERT genetics, molecular basis of inheritance, and biotechnology applications.",
      qualification: "M.Sc Biochemistry",
      experienceYears: 8
    },
    {
      id: "tut-kp-044",
      name: "Sandip Dhorde",
      title: "M.Sc Chemistry | 12th Electrochemistry & Thermodynamics Specialist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      location: "Yeshwant Nagar, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1250,
      rating: 4.96,
      totalReviews: 70,
      subjects: ["Chemistry"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "14 years experience teaching physical & inorganic chemistry to 12th board & CET students in Kopargaon.",
      qualification: "M.Sc Physical Chemistry",
      experienceYears: 14
    },
    {
      id: "tut-kp-045",
      name: "Vaishali Gholap",
      title: "M.Sc Mathematics | 12th Probability, Vectors & 3D Geometry",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80",
      location: "Tilak Nagar, Kopargaon",
      mode: "Online Only",
      hourlyRate: 1120,
      rating: 4.89,
      totalReviews: 38,
      subjects: ["Mathematics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Detailed step-by-step problem solver for 12th CBSE/State Board linear programming, probability distributions & 3D lines.",
      qualification: "M.Sc Mathematics",
      experienceYears: 9
    },
    {
      id: "tut-kp-046",
      name: "Nilesh Pawar",
      title: "B.E. Electronics | 11th & 12th Computer Science C++ & Python",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      location: "Sanjivani Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1050,
      rating: 4.88,
      totalReviews: 36,
      subjects: ["Computer Science"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Teaches 11th & 12th CS practicals, SQL database commands, networking protocols, and C++/Python coding projects.",
      qualification: "B.E. Electronics",
      experienceYears: 8
    },
    {
      id: "tut-kp-047",
      name: "Shubhangi Musale",
      title: "M.Com, B.Ed | 11th/12th Economics & Secretarial Practice Specialist",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      location: "Bus Stand Road, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 1000,
      rating: 4.90,
      totalReviews: 45,
      subjects: ["Accountancy & Economics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "10 years teaching 12th Commerce subjects in Kopargaon. Specializes in microeconomics demand curves & corporate finance.",
      qualification: "M.Com, B.Ed",
      experienceYears: 10
    },
    {
      id: "tut-kp-048",
      name: "Dipak Gaikwad",
      title: "M.Sc Botany | 12th NEET Biology Reproduction & Genetics Coach",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80",
      location: "Kopargaon Station Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1280,
      rating: 4.94,
      totalReviews: 63,
      subjects: ["Biology"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["CBSE", "State Board"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Senior NEET biology faculty. Guides students through plant physiology, human reproduction, and biotechnology diagrams.",
      qualification: "M.Sc Botany",
      experienceYears: 11
    },
    {
      id: "tut-kp-049",
      name: "Sarita Lande",
      title: "M.Sc Physical Chemistry | 12th Solutions & Electrochemistry Expert",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      location: "Shirdi Highway, Kopargaon",
      mode: "In-Person Only",
      hourlyRate: 1150,
      rating: 4.91,
      totalReviews: 42,
      subjects: ["Chemistry"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Focuses on 12th Board numerical problems in chemical kinetics, solutions, surface chemistry, and d-block elements.",
      qualification: "M.Sc Physical Chemistry",
      experienceYears: 9
    },
    {
      id: "tut-kp-050",
      name: "Harishchandra Shinde",
      title: "M.Sc Mathematics | 12th Board 100/100 Strategy Senior Coach",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80",
      location: "College Road, Kopargaon",
      mode: "Both (In-Person & Online)",
      hourlyRate: 1350,
      rating: 4.98,
      totalReviews: 96,
      subjects: ["Mathematics"],
      gradeTier: "11th to 12th Standard",
      classes: ["11th Standard", "12th Standard"],
      boards: ["State Board", "CBSE", "ICSE"],
      isVerified: true,
      degreeVerified: true,
      kycStatus: "APPROVED",
      bio: "Veteran 16-year senior mathematics coach in Kopargaon. Produced 40+ students scoring 98+ in 12th Board Mathematics.",
      qualification: "M.Sc Mathematics, B.Ed",
      experienceYears: 16
    }
  ],
  demoRequests: [
    {
      id: "demo-801",
      parentName: "Sanjay Singhania",
      studentGrade: "Grade 10",
      subject: "Mathematics",
      tutorId: "tut-kp-001",
      tutorName: "Dr. Rajesh Deshmukh",
      requestedTime: "Tomorrow at 5:00 PM",
      mode: "Online Demo",
      status: "CONFIRMED",
      createdAt: new Date().toLocaleString()
    }
  ]
};
